# site settings, does not automatically refresh with jekyll serve
# output creates a page for each document

# url settings
url: https://makena-s.github.io/webbed-site
# baseurl: /webbed-site

# site collections
collections:
  coolpages:
    output: true

# front matter defaults, ex: automatically assign layouts to specific page types
defaults:
  - scope:
      path: ""
      type: "coolpages"
    values:
      layout: "coolpage"
  - scope:
      path: ""
    values:
      layout: "default"

# exclude files you don't want in build/output
exclude:
  - ZZZ NOTES
