# site settings, does not automatically refresh with jekyll serve
# output creates a page for each document

# site collections
collections:
  coolpages:
    output: true

# front matter defaults, ex: automatically assign layouts to specific page types
defaults:
  - scope:
      path: ""
      type: "coolpages"
    values:
      layout: "coolpage"
  - scope:
      path: ""
    values:
      layout: "default"
