# site settings, does not automatically refresh with jekyll serve

# url settings
# adding baseurl to url does not automatically prepend it to links
url: https://makena-s.github.io
baseurl: /webbed-site

# site collections
collections:
  coolpages:
    output: true # output creates a page for each document

# front matter defaults, automatically add values to front matter (ex: assign layouts to specific page types)
# scope = WHICH files to add to, values = WHAT values to add
# general paths are overriden by more specific ones, which are overriden by in-file front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "" # select all files in project
      type: "coolpages" # optional, select file type within chosen path
    values: # can add your own values, ex: "author"
      layout: "coolpage"
